name: Metrics


on:
schedule:
- cron: "30 1 * * *" # daily
workflow_dispatch:


jobs:
github-metrics:
runs-on: ubuntu-latest
steps:
- uses: lowlighter/metrics@latest
with:
# A classic fine-grained PAT with public_repo (or just repo) is enough for public data
token: ${{ secrets.METRICS_TOKEN }}


# Basic
user: raytrifeno
template: classic
base: header, repositories
config_timezone: Asia/Jakarta
filename: assets/metrics.svg


# Plugins (choose your vibe)
plugin_isocalendar: yes
plugin_isocalendar_duration: full-year

plugin_habits: yes
plugin_habits_from: 200
plugin_habits_days: 14
plugin_habits_charts: yes
plugin_habits_trim: yes

plugin_languages: yes
plugin_languages_sections: most-used
plugin_languages_limit: 8
plugin_languages_threshold: 2%
plugin_languages_colors: github
plugin_languages_details: bytes-size, percentage

plugin_activity: yes
plugin_activity_limit: 5
plugin_activity_days: 14

plugin_notable: yes
plugin_notable_from: organization