name: Metrics

on:
  schedule:
    - cron: "30 1 * * *"     # harian
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure assets dir
        run: mkdir -p assets

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: raytrifeno
          template: classic
          base: header, repositories
          config_timezone: Asia/Jakarta
          filename: assets/metrics.svg

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
